- name: "SCORED | 1.1.1 | AUDIT | Create Separate Partition for /tmp"
  shell: mount | grep "on /tmp "
  register: tmp_mounted_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_1.1.1

- name: "SCORED | 1.1.5 | AUDIT | Create Separate Partition for /var"
  shell: mount | grep "on /var "
  register: var_mounted_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_1.1.5

- name: "SCORED | 1.1.7 | AUDIT | Create Separate Partition for /var/log"
  shell: mount | grep "on /var/log "
  register: varlog_mounted_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_1.1.7

- name: "SCORED | 1.1.8 | AUDIT | Create Separate Partition for /var/log/audit"
  shell: mount | grep "on /var/log/audit "
  register: varlogaudit_mounted_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_1.1.8

- name: "SCORED | 1.1.9 | AUDIT | Create Separate Partition for /home"
  shell: mount | grep "on /home "
  register: home_mounted_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_1.1.9