- name: "NOTSCORED | 9.1.1 | AUDIT | Verify System File Permissions"
  # rpm -Va --nomtime --nosize --nomd5 --nolinkto > perm_check.log
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level2
      - audit
      - rule_9.1.1

- name: "NOTSCORED | 9.1.1 | PATCH | Verify System File Permissions"
  command: /bin/true
  tags:
      - level2
      - patch
      - rule_9.1.1

- name: "SCORED | 9.1.2 | AUDIT | Verify Permissions on /etc/passwd"
  shell: stat -L -c "%a %u %g" /etc/hosts.allow | egrep "644 0 0"
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.1.2

- name: "SCORED | 9.1.2 | PATCH | Verify Permissions on /etc/passwd"
  file:
      dest=/etc/passwd
      mode=0644
  tags:
      - level1
      - level2
      - patch
      - rule_9.1.2

- name: "SCORED | 9.1.3 | AUDIT | Verify Permissions on /etc/shadow"
  shell: stat -L -c "%a %u %g" /etc/hosts.allow | egrep "640 0 0"
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.1.3

- name: "SCORED | 9.1.3 | PATCH | Verify Permissions on /etc/shadow"
  file:
      dest=/etc/shadow
      mode=000
  tags:
      - level1
      - level2
      - patch
      - rule_9.1.3

- name: "SCORED | 9.1.4 | AUDIT | Verify Permissions on /etc/gshadow"
  shell: stat -L -c "%a %u %g" /etc/hosts.allow | egrep "0 0 0"
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.1.4

- name: "SCORED | 9.1.4 | PATCH | Verify Permissions on /etc/gshadow"
  file:
      dest=/etc/gshadow
      mode=000
  tags:
      - level1
      - level2
      - patch
      - rule_9.1.4

- name: "SCORED | 9.1.5 | AUDIT | Verify Permissions on /etc/group"
  shell: stat -L -c "%a %u %g" /etc/hosts.allow | egrep "644 0 0"
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.1.5

- name: "SCORED | 9.1.5 | PATCH | Verify Permissions on /etc/group"
  file:
      dest=/etc/group
      mode=0644
  tags:
      - level1
      - level2
      - patch
      - rule_9.1.5

- name: "SCORED | 9.1.6 | AUDIT | Verify User/Group Ownership on /etc/passwd"
  shell: stat -L -c "%u %g" /etc/passwd | egrep "0 0"
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.1.6

- name: "SCORED | 9.1.6 | PATCH | Verify User/Group Ownership on /etc/passwd"
  file:
      dest=/etc/passwd
      owner=root
      group=root
  tags:
      - level1
      - level2
      - patch
      - rule_9.1.6

- name: "SCORED | 9.1.7 | AUDIT | Verify User/Group Ownership on /etc/shadow"
  shell: stat -L -c "%u %g" /etc/shadow | egrep "0 0"
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.1.7

- name: "SCORED | 9.1.7 | PATCH | Verify User/Group Ownership on /etc/shadow"
  file:
      dest=/etc/shadow
      owner=root
      group=root
  tags:
      - level1
      - level2
      - patch
      - rule_9.1.7

- name: "SCORED | 9.1.8 | AUDIT | Verify User/Group Ownership on /etc/gshadow"
  shell: stat -L -c "%u %g" /etc/gshadow | egrep "0 0"
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.1.8

- name: "SCORED | 9.1.8 | PATCH | Verify User/Group Ownership on /etc/gshadow"
  file:
      dest=/etc/gshadow
      owner=root
      group=root
  tags:
      - level1
      - level2
      - patch
      - rule_9.1.8

- name: "SCORED | 9.1.9 | AUDIT | Verify User/Group Ownership on /etc/group"
  shell: stat -L -c "%u %g" /etc/group | egrep "0 0"
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.1.9

- name: "SCORED | 9.1.9 | PATCH | Verify User/Group Ownership on /etc/group"
  file:
      dest=/etc/group
      owner=root
      group=root
  tags:
      - level1
      - level2
      - patch
      - rule_9.1.9

- name: "NOTSCORED | 9.1.10 | AUDIT | Find World Writable Files"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.1.10

- name: "NOTSCORED | 9.1.10 | PATCH | Find World Writable Files"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_9.1.10

- name: "SCORED | 9.1.11 | AUDIT | Find Un-owned Files and Directories"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.1.11

- name: "SCORED | 9.1.11 | PATCH | Find Un-owned Files and Directories"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_9.1.11

- name: "SCORED | 9.1.12 | AUDIT | Find Un-grouped Files and Directories"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.1.12

- name: "SCORED | 9.1.12 | PATCH | Find Un-grouped Files and Directories"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_9.1.12

- name: "NOTSCORED | 9.1.13 | AUDIT | Find SUID System Executables"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.1.13

- name: "NOTSCORED | 9.1.13 | PATCH | Find SUID System Executables"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_9.1.13

- name: "NOTSCORED | 9.1.14 | AUDIT | Find SGID System Executables"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.1.14

- name: "NOTSCORED | 9.1.14 | PATCH | Find SGID System Executables"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_9.1.14

- name: "SCORED | 9.2.1 | AUDIT | Ensure Password Fields are Not Empty"
  shell: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.2.1

- name: "SCORED | 9.2.1 | PATCH | Ensure Password Fields are Not Empty"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_9.2.1

- name: "SCORED | 9.2.2 | AUDIT | Verify No Legacy '+' Entries Exist in /etc/passwd File"
  command: /bin/grep '^+:' /etc/passwd
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.2.2

- name: "SCORED | 9.2.2 | PATCH | Verify No Legacy '+' Entries Exist in /etc/passwd File"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_9.2.2

- name: "SCORED | 9.2.3 | AUDIT | Verify No Legacy '+' Entries Exist in /etc/shadow File"
  command: /bin/grep '^+:' /etc/shadow
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.2.3

- name: "SCORED | 9.2.3 | PATCH | Verify No Legacy '+' Entries Exist in /etc/shadow File"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_9.2.3

- name: "SCORED | 9.2.4 | AUDIT | Verify No Legacy '+' Entries Exist in /etc/group File"
  command: /bin/grep '^+:' /etc/group
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.2.4

- name: "SCORED | 9.2.4 | PATCH | Verify No Legacy '+' Entries Exist in /etc/group File"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_9.2.4

- name: "SCORED | 9.2.5 | AUDIT | Verify No UID 0 Accounts Exist Other Than root"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.2.5

- name: "SCORED | 9.2.5 | PATCH | Verify No UID 0 Accounts Exist Other Than root"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_9.2.5

- name: "SCORED | 9.2.6 | AUDIT | Ensure root PATH Integrity"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.2.6

- name: "SCORED | 9.2.6 | PATCH | Ensure root PATH Integrity"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_9.2.6

- name: "SCORED | 9.2.7 | AUDIT | Check Permissions on User Home Directories"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.2.7

- name: "SCORED | 9.2.7 | PATCH | Check Permissions on User Home Directories"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_9.2.7

- name: "SCORED | 9.2.8 | AUDIT | Check User Dot File Permissions"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.2.8

- name: "SCORED | 9.2.8 | PATCH | Check User Dot File Permissions"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_9.2.8

- name: "SCORED | 9.2.9 | AUDIT | Check Permissions on User .netrc Files"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.2.9

- name: "SCORED | 9.2.9 | PATCH | Check Permissions on User .netrc Files"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_9.2.9

- name: "SCORED | 9.2.10 | AUDIT | Check for Presence of User .rhosts Files"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.2.10

- name: "SCORED | 9.2.10 | PATCH | Check for Presence of User .rhosts Files"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_9.2.10

- name: "SCORED | 9.2.11 | AUDIT | Check Groups in /etc/passwd"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.2.11

- name: "SCORED | 9.2.11 | PATCH | Check Groups in /etc/passwd"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_9.2.11

- name: "SCORED | 9.2.12 | AUDIT | Check That Users Are Assigned Valid Home Directories"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.2.12

- name: "SCORED | 9.2.12 | PATCH | Check That Users Are Assigned Valid Home Directories"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_9.2.12

- name: "SCORED | 9.2.13 | AUDIT | Check User Home Directory Ownership"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.2.13

- name: "SCORED | 9.2.13 | PATCH | Check User Home Directory Ownership"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_9.2.13

- name: "SCORED | 9.2.14 | AUDIT | Check for Duplicate UIDs"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.2.14

- name: "SCORED | 9.2.14 | PATCH | Check for Duplicate UIDs"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_9.2.14

- name: "SCORED | 9.2.15 | AUDIT | Check for Duplicate GIDs"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.2.15

- name: "SCORED | 9.2.15 | PATCH | Check for Duplicate GIDs"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_9.2.15

- name: "SCORED | 9.2.16 | AUDIT | Check That Reserved UIDs Are Assigned to System Accounts"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.2.16

- name: "SCORED | 9.2.16 | PATCH | Check That Reserved UIDs Are Assigned to System Accounts"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_9.2.16

- name: "SCORED | 9.2.17 | AUDIT | Check for Duplicate User Names"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.2.17

- name: "SCORED | 9.2.17 | PATCH | Check for Duplicate User Names"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_9.2.17

- name: "SCORED | 9.2.18 | AUDIT | Check for Duplicate Group Names"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.2.18

- name: "SCORED | 9.2.18 | PATCH | Check for Duplicate Group Names"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_9.2.18

- name: "SCORED | 9.2.19 | AUDIT | Check for Presence of User .netrc Files"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.2.19

- name: "SCORED | 9.2.19 | PATCH | Check for Presence of User .netrc Files"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_9.2.19

- name: "SCORED | 9.2.20 | AUDIT | Check for Presence of User .forward Files"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_9.2.20

- name: "SCORED | 9.2.20 | PATCH | Check for Presence of User .forward Files"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_9.2.20

