- name: "SCORED | 2.1.1 | AUDIT | Remove telnet-server"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.1

- name: "SCORED | 2.1.1 | PATCH | Remove telnet-server"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.1

- name: "SCORED | 2.1.2 | AUDIT | Remove telnet Clients"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.2

- name: "SCORED | 2.1.2 | PATCH | Remove telnet Clients"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.2

- name: "SCORED | 2.1.3 | AUDIT | Remove rsh-server"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.3

- name: "SCORED | 2.1.3 | PATCH | Remove rsh-server"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.3

- name: "SCORED | 2.1.4 | AUDIT | Remove rsh"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.4

- name: "SCORED | 2.1.4 | PATCH | Remove rsh"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.4

- name: "SCORED | 2.1.5 | AUDIT | Remove NIS Client"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.5

- name: "SCORED | 2.1.5 | PATCH | Remove NIS Client"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.5

- name: "SCORED | 2.1.6 | AUDIT | Remove NIS Server"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.6

- name: "SCORED | 2.1.6 | PATCH | Remove NIS Server"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.6

- name: "SCORED | 2.1.7 | AUDIT | Remove tftp"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.7

- name: "SCORED | 2.1.7 | PATCH | Remove tftp"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.7

- name: "SCORED | 2.1.8 | AUDIT | Remove tftp-server"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.8

- name: "SCORED | 2.1.8 | PATCH | Remove tftp-server"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.8

- name: "SCORED | 2.1.9 | AUDIT | Remove talk"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.9

- name: "SCORED | 2.1.9 | PATCH | Remove talk"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.9

- name: "SCORED | 2.1.10 | AUDIT | Remove talk-server"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.10

- name: "SCORED | 2.1.10 | PATCH | Remove talk-server"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.10

- name: "SCORED | 2.1.11 | AUDIT | Remove xinetd"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level2
      - audit
      - rule_2.1.11

- name: "SCORED | 2.1.11 | PATCH | Remove xinetd"
  command: /bin/true
  tags:
      - level2
      - patch
      - rule_2.1.11

- name: "SCORED | 2.1.12 | AUDIT | Disable chargen-dgram"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.12

- name: "SCORED | 2.1.12 | PATCH | Disable chargen-dgram"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.12

- name: "SCORED | 2.1.13 | AUDIT | Disable chargen-stream"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.13

- name: "SCORED | 2.1.13 | PATCH | Disable chargen-stream"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.13

- name: "SCORED | 2.1.14 | AUDIT | Disable daytime-dgram"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.14

- name: "SCORED | 2.1.14 | PATCH | Disable daytime-dgram"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.14

- name: "SCORED | 2.1.15 | AUDIT | Disable daytime-stream"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.15

- name: "SCORED | 2.1.15 | PATCH | Disable daytime-stream"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.15

- name: "SCORED | 2.1.16 | AUDIT | Disable echo-dgram"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.16

- name: "SCORED | 2.1.16 | PATCH | Disable echo-dgram"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.16

- name: "SCORED | 2.1.17 | AUDIT | Disable echo-stream"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.17

- name: "SCORED | 2.1.17 | PATCH | Disable echo-stream"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.17

- name: "SCORED | 2.1.18 | AUDIT | Disable tcpmux-server"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_2.1.18

- name: "SCORED | 2.1.18 | PATCH | Disable tcpmux-server"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_2.1.18

