- name: "SCORED | 3.1.1 | AUDIT | Ensure IP forwarding is disabled"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.1.1

- name: "SCORED | 3.1.1 | PATCH | Ensure IP forwarding is disabled"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.1.1

- name: "SCORED | 3.1.2 | AUDIT | Ensure packet redirect sending is disabled"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.1.2

- name: "SCORED | 3.1.2 | PATCH | Ensure packet redirect sending is disabled"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.1.2

- name: "SCORED | 3.2.1 | AUDIT | Ensure source routed packets are not accepted"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.2.1

- name: "SCORED | 3.2.1 | PATCH | Ensure source routed packets are not accepted"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.2.1

- name: "SCORED | 3.2.2 | AUDIT | Ensure ICMP redirects are not accepted"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.2.2

- name: "SCORED | 3.2.2 | PATCH | Ensure ICMP redirects are not accepted"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.2.2

- name: "SCORED | 3.2.3 | AUDIT | Ensure secure ICMP redirects are not accepted"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.2.3

- name: "SCORED | 3.2.3 | PATCH | Ensure secure ICMP redirects are not accepted"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.2.3

- name: "SCORED | 3.2.4 | AUDIT | Ensure suspicious packets are logged"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.2.4

- name: "SCORED | 3.2.4 | PATCH | Ensure suspicious packets are logged"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.2.4

- name: "SCORED | 3.2.5 | AUDIT | Ensure broadcast ICMP requests are ignored"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.2.5

- name: "SCORED | 3.2.5 | PATCH | Ensure broadcast ICMP requests are ignored"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.2.5

- name: "SCORED | 3.2.6 | AUDIT | Ensure bogus ICMP responses are ignored"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.2.6

- name: "SCORED | 3.2.6 | PATCH | Ensure bogus ICMP responses are ignored"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.2.6

- name: "SCORED | 3.2.7 | AUDIT | Ensure Reverse Path Filtering is enabled"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.2.7

- name: "SCORED | 3.2.7 | PATCH | Ensure Reverse Path Filtering is enabled"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.2.7

- name: "SCORED | 3.2.8 | AUDIT | Ensure TCP SYN Cookies is enabled"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.2.8

- name: "SCORED | 3.2.8 | PATCH | Ensure TCP SYN Cookies is enabled"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.2.8

- name: "SCORED | 3.3.1 | AUDIT | Ensure IPv6 router advertisements are not accepted"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.3.1

- name: "SCORED | 3.3.1 | PATCH | Ensure IPv6 router advertisements are not accepted"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.3.1

- name: "SCORED | 3.3.2 | AUDIT | Ensure IPv6 redirects are not accepted"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.3.2

- name: "SCORED | 3.3.2 | PATCH | Ensure IPv6 redirects are not accepted"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.3.2

- name: "NOTSCORED | 3.3.3 | AUDIT | Ensure IPv6 is disabled"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.3.3

- name: "NOTSCORED | 3.3.3 | PATCH | Ensure IPv6 is disabled"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.3.3

- name: "SCORED | 3.4.1 | AUDIT | Ensure TCP Wrappers is installed"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.4.1

- name: "SCORED | 3.4.1 | PATCH | Ensure TCP Wrappers is installed"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.4.1

- name: "SCORED | 3.4.2 | AUDIT | Ensure /etc/hosts.allow is configured"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.4.2

- name: "SCORED | 3.4.2 | PATCH | Ensure /etc/hosts.allow is configured"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.4.2

- name: "SCORED | 3.4.3 | AUDIT | Ensure /etc/hosts.deny is configured"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.4.3

- name: "SCORED | 3.4.3 | PATCH | Ensure /etc/hosts.deny is configured"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.4.3

- name: "SCORED | 3.4.4 | AUDIT | Ensure permissions on /etc/hosts.allow are configured"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.4.4

- name: "SCORED | 3.4.4 | PATCH | Ensure permissions on /etc/hosts.allow are configured"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.4.4

- name: "SCORED | 3.4.5 | AUDIT | Ensure permissions on /etc/hosts.deny are 644"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.4.5

- name: "SCORED | 3.4.5 | PATCH | Ensure permissions on /etc/hosts.deny are 644"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.4.5

- name: "NOTSCORED | 3.5.1 | AUDIT | Ensure DCCP is disabled"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.5.1

- name: "NOTSCORED | 3.5.1 | PATCH | Ensure DCCP is disabled"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.5.1

- name: "NOTSCORED | 3.5.2 | AUDIT | Ensure SCTP is disabled"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.5.2

- name: "NOTSCORED | 3.5.2 | PATCH | Ensure SCTP is disabled"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.5.2

- name: "NOTSCORED | 3.5.3 | AUDIT | Ensure RDS is disabled"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.5.3

- name: "NOTSCORED | 3.5.3 | PATCH | Ensure RDS is disabled"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.5.3

- name: "NOTSCORED | 3.5.4 | AUDIT | Ensure TIPC is disabled"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.5.4

- name: "NOTSCORED | 3.5.4 | PATCH | Ensure TIPC is disabled"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.5.4

- name: "SCORED | 3.6.1 | AUDIT | Ensure iptables is installed"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.6.1

- name: "SCORED | 3.6.1 | PATCH | Ensure iptables is installed"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.6.1

- name: "SCORED | 3.6.2 | AUDIT | Ensure default deny firewall policy"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.6.2

- name: "SCORED | 3.6.2 | PATCH | Ensure default deny firewall policy"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.6.2

- name: "SCORED | 3.6.3 | AUDIT | Ensure loopback traffic is configured"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.6.3

- name: "SCORED | 3.6.3 | PATCH | Ensure loopback traffic is configured"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.6.3

- name: "NOTSCORED | 3.6.4 | AUDIT | Ensure outbound and established connections are configured"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.6.4

- name: "NOTSCORED | 3.6.4 | PATCH | Ensure outbound and established connections are configured"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.6.4

- name: "SCORED | 3.6.5 | AUDIT | Ensure firewall rules exist for all open ports"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.6.5

- name: "SCORED | 3.6.5 | PATCH | Ensure firewall rules exist for all open ports"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.6.5

- name: "NOTSCORED | 3.7 | AUDIT | Ensure wireless interfaces are disabled"
  command: /bin/true
  register: result
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - level1
      - level2
      - audit
      - rule_3.7

- name: "NOTSCORED | 3.7 | PATCH | Ensure wireless interfaces are disabled"
  command: /bin/true
  tags:
      - level1
      - level2
      - patch
      - rule_3.7

